- name: Discord notification
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  uses: "Ilshidur/action-discord@0.3.0"
  with:
    args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
